import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import aitDevtools from '@apps-in-toss/devtools/unplugin';
import react from '@vitejs/plugin-react';
import { defineConfig } from 'vite';

// This config is loaded as ESM ("type": "module"), so __dirname is not defined.
// Derive it from import.meta.url instead.
const __dirname = path.dirname(fileURLToPath(import.meta.url));

const mockDist = path.resolve(__dirname, '../../dist/mock/index.js');
const panelDist = path.resolve(__dirname, '../../dist/panel/index.js');
for (const p of [mockDist, panelDist]) {
  if (!fs.existsSync(p)) {
    throw new Error(
      `Required devtools dist file not found — run 'pnpm build' at the repo root first (missing: ${p})`,
    );
  }
}

// Single source of truth for the OG image is packages/devtools/assets/og/image.png
// (generated by `pnpm build:og`, also embedded by the two READMEs). The fixture's
// index.html references it at the site-relative path `/og/image.png`, so this
// plugin copies the built PNG into the fixture's dist/ output rather than a second
// copy living under e2e/fixture/public/ — a second copy would silently drift the
// next time someone reruns build:og and forgets the fixture copy (see the warning
// in scripts/build-og-image.tsx).
const OG_IMAGE_SRC = path.resolve(__dirname, '../../assets/og/image.png');
const OUT_DIR = 'dist';

function copyOgImage() {
  return {
    name: 'copy-og-image',
    apply: 'build' as const,
    closeBundle() {
      if (!fs.existsSync(OG_IMAGE_SRC)) {
        throw new Error(
          `OG image not found — run 'pnpm build:og' first (missing: ${OG_IMAGE_SRC})`,
        );
      }
      const destDir = path.resolve(__dirname, OUT_DIR, 'og');
      fs.mkdirSync(destDir, { recursive: true });
      fs.copyFileSync(OG_IMAGE_SRC, path.join(destDir, 'image.png'));
    },
  };
}

// This fixture is no longer deployed to Pages (docs/release-plan.md Phase 1
// B4 — the launcher PWA that used to live at e2e/fixture/launcher/ and ship
// at /launcher/ moved to sites/launcher/, which owns its own base-path
// handling now). base stays '/' unconditionally: this fixture only runs
// locally (`pnpm e2e:build`, `pnpm test:e2e`) going forward.
const base = '/';

export default defineConfig({
  root: __dirname,
  base,
  resolve: {
    alias: {
      // Bypass rolldown resolveId limitation: alias directly to built mock file.
      // (Panel is imported explicitly in main.tsx; unplugin panel injection is
      // disabled below because unplugin transform is unreliable under Vite 8
      // production build with rolldown.)
      //
      // Note on types: this alias only rewires the runtime import; TypeScript
      // still resolves the module via `node_modules/@apps-in-toss/web-framework`
      // (a devDependency). If that devDep is removed, `pnpm typecheck` breaks
      // for the fixture even though `pnpm test:e2e` keeps working.
      '@apps-in-toss/web-framework': mockDist,
    },
  },
  // mock, panel, inApp are all disabled — active transform work is handled
  // explicitly in main.tsx (bypasses rolldown/Vite 8 transform reliability issue).
  //   mock:  off — handled by resolve.alias above (bypasses rolldown resolveId bug)
  //   panel: off — handled by explicit import in main.tsx
  //   inApp: off — handled by explicit in-app snippet in main.tsx
  // The plugin is kept in the list for tunnel support (manual QA only).
  plugins: [
    react(),
    aitDevtools.vite({
      panel: false,
      mock: false,
      inApp: false,
      // Manual QA toggles only — no effect on CI / normal builds.
      // AIT_TUNNEL=1       → plain HTTP tunnel only (env-2 screen preview)
      // AIT_TUNNEL_CDP=1   → HTTP tunnel + Chii relay + relay tunnel (env-2 CDP)
      tunnel: process.env.AIT_TUNNEL_CDP ? { cdp: true } : !!process.env.AIT_TUNNEL,
    }),
    copyOgImage(),
  ],
  preview: {
    port: 4173,
    strictPort: true,
  },
  build: {
    outDir: OUT_DIR,
    emptyOutDir: true,
    rollupOptions: {
      input: {
        // Single entry — the devtools panel demo (e2e/panel.test.ts). The
        // launcher PWA entry that used to live here moved to sites/launcher/
        // (build config: packages/devtools/e2e/launcher-site.vite.config.ts,
        // docs/release-plan.md Phase 1 B4).
        index: path.resolve(__dirname, 'index.html'),
      },
    },
  },
});
